FROM golang:1.21-alpine

RUN set -ex && \
    apk update && \
    apk add gcc libc-dev git

COPY . /go/src/github.com/ishantt/docker-ipam-plugin
WORKDIR /go/src/github.com/ishantt/docker-ipam-plugin

RUN set -ex && \
    go install
CMD ["/go/bin/docker-ipam-plugin"]
